# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shipping_address', '0003_auto_20160115_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 15, 4, 46, 32, 963785)),
        ),
    ]
