# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
