# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='coupon_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
