# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 15, 4, 25, 3, 207480)),
        ),
    ]
