# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160115_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 15, 7, 59, 53, 550023)),
        ),
    ]
