# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160115_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 16, 7, 19, 37, 917588)),
        ),
    ]
